name: unspash

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - 8443:80
    env_file:
      - .env
    networks:
      - app_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - app_network


networks:
  app_network:
    name: app_network
    driver: bridge